framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system

when@test:
    framework:
        cache:
            app: cache.adapter.array
            system: cache.adapter.system
